title = "Stuckcode"
theme = "heyo"
baseURL = "/"
languageCode = "id"
DefaultContentLanguage = "id"
summarylength = 100
enableEmoji = true
enableRobotsTXT = true
paginate = 10
timeZone = "Asia/Jakarta"

# Disqus comments
# https://gohugo.io/templates/internal/#configure-disqus
# disqusShortname = ""

# Google Analytics
# https://gohugo.io/templates/internal/#google-analytics
# googleAnalytics = ""

[Languages]
  [Languages.en]
    contentDir = "content/en"
    weight = 1
    LanguageName = "en"

  [Languages.id]
    contentDir = "content/id"
    weight = 2
    LanguageName = "id"
    

[params.author]
  name = "Naka Rhythm"
  email = "0xnaka@duck.com"

[params]
  title = "I'm Naka Rhythm"
  description = "Call me Naka"
  profilePicture = "images/profile.png"
  favicon = "favicons/"
  customCss = []
  customJs = []
  displayMode = "dark"
  images = ['images/profile.png']

[taxonomies]
  series = 'series'

# Sketch settings
# you can also enable or disable it per page
[params.sketch] 
  enable = true 
  displayOptions = false
  # Graph, Digital Rain, or Circles
  use = "Digital Rain"
  # JSON that is passed to the sketch constructor
  # You can check all the possible configurations in
  startingConfig = """{
    "kind": "random",
    "nStreams": 10
  }"""


## Math settings
[params.math]
  # global support, you can also configure it per page
  enable = true
  # katex or mathjax, default is mathjax
  use = "mathjax"

## Social links
[[params.socialIcons]]
icon = "fab fa-linkedin" # Font-awesome icon
title = "Linkedin"
url = "https://linkedin.com/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/Nakasz"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:0xnaka@duck.com"

# Menu items
[menu]
[[Languages.en.menu.main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[Languages.en.menu.main]]
name = "Posts"
weight = 200
identifier = "posts"
url = "/post/"

[[Languages.en.menu.main]]
name = "About"
weight = 300
identifier = "about"
url = "/about/"

[[Languages.id.menu.main]]
name = "Beranda"
identifier = "home"
weight = 100
url = "/id/"

[[Languages.id.menu.main]]
name = "Blog"
weight = 200
identifier = "posts"
url = "/post/"

[[Languages.id.menu.main]]
name = "Tentang"
weight = 300
identifier = "about"
url = "/about/"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    endLevel = 6
    startLevel = 1
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4

# Hugo will ignore these files, .rmd and .rmarkdown are taken care by blogdown
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown", "_files$", "_cache$"]